### ISSUE TITLE
SAR图像和可见光遥感图像并不完全对应

### ISSUE THREAD

**Issue by windyjunfeng** [yaoxu008/QXS-SAROPT#7]
![19477](https://user-images.githubusercontent.com/58356387/178134364-96e4c938-6870-42be-bcd1-6e044103958e.png)
![19477](https://user-images.githubusercontent.com/58356387/178134385-5746f853-9224-4909-b623-121c0f9e8dfe.png)
您好，请问数据集中的SAR和可见光光图片是不是有些并不完全对应呢（比如不是同一个时间点的）？比如上面一对图片，感觉SAR图像比可见光图像少了一艘舰船，不像是配准的问题。谢谢~

**Comment by yaoxu008** [comment]
您好，
不好意思现在才回复。我们无法找到完全时空对齐的光sar匹配数据。目前只保证了两者的空间配准，而光sar成像时间可能会有较大的差距。一些目标的移动会造成图像的区别，请见谅。

--------------原始邮件--------------
发件人："windyjunfeng ***@***.***&gt;;
发送时间：2022年7月10日(星期天) 下午2:56
收件人："yaoxu008/QXS-SAROPT" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[yaoxu008/QXS-SAROPT] SAR图像和可见光遥感图像并不完全对应 (Issue #7)
-----------------------------------

 

 

 
 您好，请问数据集中的SAR和可见光光图片是不是有些并不完全对应呢（比如不是同一个时间点的）？比如上面一对图片，感觉SAR图像比可见光图像少了一艘舰船，不像是配准的问题。谢谢~

**Comment by windyjunfeng** [comment]
好的，谢谢~

**Comment by javey-q** [comment]
为什么我感觉有的图片确实是没有配准呢？比较明显的如下：
![image](https://github.com/yaoxu008/QXS-SAROPT/assets/49089869/cabda515-e824-482c-91fc-61613cadbe3c)
![image](https://github.com/yaoxu008/QXS-SAROPT/assets/49089869/9cecad3c-25be-4e4d-8775-dcf5be3e39ed)
![image](https://github.com/yaoxu008/QXS-SAROPT/assets/49089869/ae0bd1f6-62fb-4327-8090-7af509840f83)
![image](https://github.com/yaoxu008/QXS-SAROPT/assets/49089869/7f4dc7d1-05c0-4dbf-af35-752fc977b9c3)
感觉这些图片附近的都存在偏移问题
